# Generated by Django 5.0.6 on 2024-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_cust_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_feature', models.CharField(default='about main feature', max_length=100)),
                ('descriptions', models.TextField(default='description')),
            ],
        ),
    ]
