# Generated by Django 5.0.6 on 2024-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='name of services', max_length=200)),
                ('description_services', models.TextField(default='description of services')),
            ],
        ),
    ]
