# Generated by Django 5.0.6 on 2024-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_choose_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='reason points why choose us', max_length=200)),
                ('description_whychooseus', models.TextField(default='description of why choose us')),
            ],
        ),
    ]
